# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import SaveLoadManager_pb2 as SaveLoadManager__pb2

GRPC_GENERATED_VERSION = '1.66.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in SaveLoadManager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SaveLoadManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.game_list_func = channel.unary_unary(
                '/SaveLoadManager/game_list_func',
                request_serializer=SaveLoadManager__pb2.request_game_list.SerializeToString,
                response_deserializer=SaveLoadManager__pb2.response_game_list.FromString,
                _registered_method=True)
        self.profile_list_func = channel.unary_unary(
                '/SaveLoadManager/profile_list_func',
                request_serializer=SaveLoadManager__pb2.request_profile_list.SerializeToString,
                response_deserializer=SaveLoadManager__pb2.response_profile_list.FromString,
                _registered_method=True)
        self.save_list_func = channel.unary_unary(
                '/SaveLoadManager/save_list_func',
                request_serializer=SaveLoadManager__pb2.request_save_list.SerializeToString,
                response_deserializer=SaveLoadManager__pb2.response_save_list.FromString,
                _registered_method=True)
        self.game_delete = channel.unary_unary(
                '/SaveLoadManager/game_delete',
                request_serializer=SaveLoadManager__pb2.request_game_delete.SerializeToString,
                response_deserializer=SaveLoadManager__pb2.response_game_delete.FromString,
                _registered_method=True)
        self.profile_new = channel.unary_unary(
                '/SaveLoadManager/profile_new',
                request_serializer=SaveLoadManager__pb2.request_profile_new.SerializeToString,
                response_deserializer=SaveLoadManager__pb2.response_profile_new.FromString,
                _registered_method=True)
        self.profile_delete = channel.unary_unary(
                '/SaveLoadManager/profile_delete',
                request_serializer=SaveLoadManager__pb2.request_profile_delete.SerializeToString,
                response_deserializer=SaveLoadManager__pb2.response_profile_delete.FromString,
                _registered_method=True)
        self.save_new = channel.unary_unary(
                '/SaveLoadManager/save_new',
                request_serializer=SaveLoadManager__pb2.request_save_new.SerializeToString,
                response_deserializer=SaveLoadManager__pb2.response_save_new.FromString,
                _registered_method=True)
        self.save_delete = channel.unary_unary(
                '/SaveLoadManager/save_delete',
                request_serializer=SaveLoadManager__pb2.request_save_delete.SerializeToString,
                response_deserializer=SaveLoadManager__pb2.response_save_delete.FromString,
                _registered_method=True)
        self.save_load = channel.unary_unary(
                '/SaveLoadManager/save_load',
                request_serializer=SaveLoadManager__pb2.request_save_load.SerializeToString,
                response_deserializer=SaveLoadManager__pb2.response_save_load.FromString,
                _registered_method=True)


class SaveLoadManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def game_list_func(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def profile_list_func(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def save_list_func(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def game_delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def profile_new(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def profile_delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def save_new(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def save_delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def save_load(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SaveLoadManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'game_list_func': grpc.unary_unary_rpc_method_handler(
                    servicer.game_list_func,
                    request_deserializer=SaveLoadManager__pb2.request_game_list.FromString,
                    response_serializer=SaveLoadManager__pb2.response_game_list.SerializeToString,
            ),
            'profile_list_func': grpc.unary_unary_rpc_method_handler(
                    servicer.profile_list_func,
                    request_deserializer=SaveLoadManager__pb2.request_profile_list.FromString,
                    response_serializer=SaveLoadManager__pb2.response_profile_list.SerializeToString,
            ),
            'save_list_func': grpc.unary_unary_rpc_method_handler(
                    servicer.save_list_func,
                    request_deserializer=SaveLoadManager__pb2.request_save_list.FromString,
                    response_serializer=SaveLoadManager__pb2.response_save_list.SerializeToString,
            ),
            'game_delete': grpc.unary_unary_rpc_method_handler(
                    servicer.game_delete,
                    request_deserializer=SaveLoadManager__pb2.request_game_delete.FromString,
                    response_serializer=SaveLoadManager__pb2.response_game_delete.SerializeToString,
            ),
            'profile_new': grpc.unary_unary_rpc_method_handler(
                    servicer.profile_new,
                    request_deserializer=SaveLoadManager__pb2.request_profile_new.FromString,
                    response_serializer=SaveLoadManager__pb2.response_profile_new.SerializeToString,
            ),
            'profile_delete': grpc.unary_unary_rpc_method_handler(
                    servicer.profile_delete,
                    request_deserializer=SaveLoadManager__pb2.request_profile_delete.FromString,
                    response_serializer=SaveLoadManager__pb2.response_profile_delete.SerializeToString,
            ),
            'save_new': grpc.unary_unary_rpc_method_handler(
                    servicer.save_new,
                    request_deserializer=SaveLoadManager__pb2.request_save_new.FromString,
                    response_serializer=SaveLoadManager__pb2.response_save_new.SerializeToString,
            ),
            'save_delete': grpc.unary_unary_rpc_method_handler(
                    servicer.save_delete,
                    request_deserializer=SaveLoadManager__pb2.request_save_delete.FromString,
                    response_serializer=SaveLoadManager__pb2.response_save_delete.SerializeToString,
            ),
            'save_load': grpc.unary_unary_rpc_method_handler(
                    servicer.save_load,
                    request_deserializer=SaveLoadManager__pb2.request_save_load.FromString,
                    response_serializer=SaveLoadManager__pb2.response_save_load.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SaveLoadManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('SaveLoadManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SaveLoadManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def game_list_func(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SaveLoadManager/game_list_func',
            SaveLoadManager__pb2.request_game_list.SerializeToString,
            SaveLoadManager__pb2.response_game_list.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def profile_list_func(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SaveLoadManager/profile_list_func',
            SaveLoadManager__pb2.request_profile_list.SerializeToString,
            SaveLoadManager__pb2.response_profile_list.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def save_list_func(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SaveLoadManager/save_list_func',
            SaveLoadManager__pb2.request_save_list.SerializeToString,
            SaveLoadManager__pb2.response_save_list.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def game_delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SaveLoadManager/game_delete',
            SaveLoadManager__pb2.request_game_delete.SerializeToString,
            SaveLoadManager__pb2.response_game_delete.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def profile_new(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SaveLoadManager/profile_new',
            SaveLoadManager__pb2.request_profile_new.SerializeToString,
            SaveLoadManager__pb2.response_profile_new.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def profile_delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SaveLoadManager/profile_delete',
            SaveLoadManager__pb2.request_profile_delete.SerializeToString,
            SaveLoadManager__pb2.response_profile_delete.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def save_new(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SaveLoadManager/save_new',
            SaveLoadManager__pb2.request_save_new.SerializeToString,
            SaveLoadManager__pb2.response_save_new.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def save_delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SaveLoadManager/save_delete',
            SaveLoadManager__pb2.request_save_delete.SerializeToString,
            SaveLoadManager__pb2.response_save_delete.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def save_load(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SaveLoadManager/save_load',
            SaveLoadManager__pb2.request_save_load.SerializeToString,
            SaveLoadManager__pb2.response_save_load.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
